# Header
menu:
  Home: /
  Archives: /archives
  About: /about.html

# Logo Image Source
logo_src: /images/icon48.png

# Theme Main Subtitle
subtitle_main: This is Akaton, our little adventure log book.

# Theme Secondary subtitle
susbtitle_secondary: We live in a fast pace environment so why not slow down with a sailboat to enjoy life a bit. So with no experience at all we decided to look for sailboat that people consider mad to start with! Most people start with a Lazer or anything of 3-4 meter to learn, but nop, when we do something we go all in! So let's start with a BIG 12.8m 9ton boat with no boat experience.

# Footer About Section
about_footer: Already to the bottom? Checkout the other blog post!

# Default post title
default_post_title: Untitled

# Default post cover index page (Recommended)
default_cover_index: "https://placekitten.com/450/450"

# Default post cover index page (Optional)
default_cover_detail:

# Show Dates for posts and pages
show_dates: true

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname: klugjo
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
twitter_url: https://twitter.com/?lang=en
facebook_url: https://www.facebook.com/
instagram_url: https://www.instagram.com/
dribble_url: https://dribbble.com/
github_url: https://github.com/klugjo/hexo-theme-phantom/commits?author=klugjo
googleplus_url: https://plus.google.com/
behance_url: https://www.behance.net/
fivehundredpx_url: https://500px.com/
email_url: \#
rss_url: \#
